name: premium_chat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # انٹرنیٹ اور بیک اینڈ سے بات کرنے کے لیے
  http: ^1.1.0
  
  # تصاویر منتخب کرنے کے لیے (پروفائل سیٹ اپ کے لیے لازمی)
  image_picker: ^1.1.0
  
  # ڈیٹا لوکل اسٹوریج میں محفوظ کرنے کے لیے (UUID اور لاگ ان کے لیے)
  shared_preferences: ^2.2.3

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
