name: NoorApp
description: "A premium webview application."
publish_to: 'none'

version: 1.0.0+1

environment:
  # یہ ورژن ہر جگہ (GitHub اور آپ کے کمپیوٹر) پر چل جائے گا
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  
  # ہم نے یہاں '^' کا نشان لگا دیا ہے تاکہ GitHub لیٹسٹ ورژن اٹھائے اور کوڈ چل جائے
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.0.0
  webview_flutter_wkwebview: ^3.15.0
  
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
