name: Ultimate Auto-Fix and Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java and Flutter
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Fresh Rebuild and Package Fix
        run: |
          # 1. پرانا کچرا صاف کرنا
          rm -rf android
          
          # 2. نیا لیٹسٹ پروجیکٹ بنانا
          flutter create . --platforms android
          
          # 3. خودکار طریقے سے فائل ڈھونڈ کر پیکج نیم بدلنا (چاہے نام .gradle ہو یا .kts)
          find android -name "build.gradle*" -exec sed -i 's/com.example.premium_chat/com.quick.designapp/g' {} +
          find android -name "MainActivity.kt" -exec sed -i 's/com.example.premium_chat/com.quick.designapp/g' {} +
          
          # 4. ورژنز کی مطابقت درست کرنا
          flutter pub get

      - name: Build APK
        run: |
          flutter build apk --release --target-platform android-arm64 --split-per-abi --android-skip-build-dependency-validation

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Final-Success-Build
          path: build/app/outputs/flutter-apk/*.apk
