name: Flutter Web Build and Deploy
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Fresh Build
        run: |
          # 1. ویب سپورٹ فعال کرنا
          flutter config --enable-web
          
          # 2. پیکجز کلین اور گیٹ کرنا
          flutter pub get
          
          # 3. ویب بلڈ بنانا (HTML رینڈرر کے ساتھ تاکہ وائٹ اسکرین نہ آئے)
          # نوٹ: --base-href کا صحیح ہونا ضروری ہے
          flutter build web --release --web-renderer html --base-href "/${{ github.event.repository.name }}/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
