name: Setup NoorApp Flutter Project

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      - name: Create Flutter WebView Project (NoorApp)
        run: flutter create NoorApp --overwrite --org com.noorapp

      - name: Configure Git
        run: |
          cd NoorApp
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Commit changes
        run: |
          cd NoorApp
          git add .
          git diff --cached --quiet || git commit -m "Auto: NoorApp Flutter WebView base setup"

      - name: Push changes
        run: |
          git push
