name: Setup NoorApp Flutter Project

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.19.6"

      - name: Create Flutter Project
        run: flutter create NoorApp --overwrite --org com.noorapp

      - name: Git setup
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Commit changes
        run: |
          git add .
          git diff --cached --quiet || git commit -m "Auto: NoorApp setup"

      - name: Push changes
        run: |
          git push
